<?php /** @var $block \Magento\Framework\View\Element\Template */?>
<?php if ($block->isEnabled()) : ?>
<div data-block="weather" class="weather-wrapper">
    <div class="weather-icon icon-weather">
        <span> <?php echo $block->getApiTime() ?> </span>
        <svg xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 640 512">
            <style>svg{fill:#175acf}</style>
            <path d="M0 336c0 79.5 64.5 144 144 144H512c70.7 0 128-57.3 128-128c0-61.9-44-113.6-102.4-125.4c4.1-10.7 6.4-22.4 6.4-34.6c0-53-43-96-96-96c-19.7 0-38.1 6-53.3 16.2C367 64.2 315.3 32 256 32C167.6 32 96 103.6 96 192c0 2.7 .1 5.4 .2 8.1C40.2 219.8 0 273.2 0 336z"/>
        </svg>
    </div>
    <span class="weather-text"><?= $block->escapeHtml(__('Weather')) ?></span>
</div>

<script type="text/javascript">
    require(['jquery', 'weather'], function($, weather) {
        $(document).ready(function () {
            $('.weather-wrapper').weatherWidget({
                urlTime: "<?php echo $block->escapeUrl($block->getUrl('rest/default/V1/weather/time')) ?>",
            });
        });
    });
</script>
<?php endif ?>
